### ISSUE TITLE
Can't play via pulse

### ISSUE THREAD

**Issue by Vaelatern** [t6/pulseaudio-module-sndio#1]
With pavucontrol, I see the sndio output device, and I see the applications connecting to pulseaudio, but I never hear the sound. `paplay` exits with an error code, explaining `Failed to drain stream: Timeout`. Confusing the issue further, sndio (via `aucatctl`) does show the `pulseau0` program as registered, so I'm not sure where my sound is getting lost.

Thank you for this module, is there any way to make it work?

**Comment by t6** [comment]
This repository is here only for the `audio/pulseaudio-module-sndio` port on FreeBSD and is tied to specific PulseAudio versions since it contains a copy of internal PulseAudio headers to make out-of-tree builds possible. Version 10.99.1 is for PulseAudio >= 10.99.1 < 12.0.

If it doesn't work try syncing the headers in `pulsecore/` with the ones from your specific version.

**Comment by Vaelatern** [comment]
Thank you, I merged them in my fork and gave it a spin. Same results, sadly.
I should mention that I'm building this on Linux, not FBSD, but I'd think pulse and sndio wouldn't change.

**Comment by Vaelatern** [comment]
I see eea8dac, I'll test that! Thank you!

**Comment by Vaelatern** [comment]
Agreed, with your changes it works well.
Thank you!
